name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Wayland development tools (only for Linux)
        if: runner.os == 'Linux' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install wayland-scanner
          
      - name: Prepare build Debug
        run: chmod +x ./scripts/build_debug.sh

      - name: Build Debug
        run: ./scripts/build_debug.sh

      - name: Prepare build Release
        run: chmod +x ./scripts/build_release.sh

      - name: Build Release
        run: ./scripts/build_release.sh
