name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Wayland development tools (only for Ubuntu)
        if: runner.os == 'Linux' && matrix.os == 'ubuntu-latest'
        run: sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
          
      - name: Build Debug
        shell: bash
        run: |
          chmod +x ./scripts/build_debug.sh
          ./scripts/build_debug.sh

      - name: Build Release
        shell: bash
        run: |
          chmod +x ./scripts/build_release.sh
          ./scripts/build_release.sh
